language: c
before_install:
  - chmod 777 valgrindinstall
  - chmod 777 run
  - ./valgrindinstall
install:
  - sudo apt-get install check
before_script:
  - autoreconf --install
script: ./run
after_success:
  - chmod 777 postinstall
  - ./postinstall
