#!/bin/bash

./configure
make
CK_FORK=no

mkdir bin
mv src/practical_trees bin/
mv tests/check_test bin/
chmod -R 777 bin
cd bin
echo "____________________START____________________"
echo "Valgrind on tests"
libtool --mode=execute valgrind --leak-check=full -v --tool=memcheck ./check_test
echo "____________________NEXT_____________________"
echo "Valgrind on program"
libtool --mode=execute valgrind --leak-check=full -v --tool=memcheck ./practical_trees
echo "____________________NEXT_____________________"
echo "Running program"
./practical_trees
echo "____________________END______________________"